#!/usr/bin/env python3
"""Fetch Tier 1 keyword metrics from Google Search Console and build docs/rankings.json.

Your ranks come from GSC (free). Competitor ranks from Google Custom Search API (free tier)
or fall back to docs/seo-dashboard-config.json (manual SERP).

Setup: docs/SEO-DASHBOARD-SETUP.md

Run:
  python3 tools/fetch_gsc_rankings.py              # GSC + CSE when env vars set
  python3 tools/fetch_gsc_rankings.py --dry-run    # config only, no API
  python3 tools/fetch_gsc_rankings.py --test-cse   # verify Custom Search credentials
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from copy import deepcopy
from datetime import date, timedelta
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
CONFIG_FILE = ROOT / "docs" / "seo-dashboard-config.json"
OUTPUT_FILE = ROOT / "docs" / "rankings.json"
EMBED_FILE = ROOT / "docs" / "rankings.embed.js"
SCOPES = ["https://www.googleapis.com/auth/webmasters.readonly"]


def load_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def save_json(path: Path, data: dict[str, Any]) -> None:
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


def save_embed_js(path: Path, data: dict[str, Any]) -> None:
    """Write JS bundle for file:// dashboard opens (fetch blocked by browser)."""
    with path.open("w", encoding="utf-8") as f:
        f.write("// Generated by tools/fetch_gsc_rankings.py — do not edit\n")
        f.write("window.RANKINGS_DATA = ")
        json.dump(data, f, ensure_ascii=False)
        f.write(";\n")


def period_ranges(days: int = 28) -> tuple[tuple[str, str], tuple[str, str]]:
    end = date.today() - timedelta(days=3)  # GSC data lag
    current_start = end - timedelta(days=days - 1)
    previous_end = current_start - timedelta(days=1)
    previous_start = previous_end - timedelta(days=days - 1)
    fmt = lambda d: d.isoformat()
    return (fmt(current_start), fmt(end)), (fmt(previous_start), fmt(previous_end))


def mom_delta(current: float | None, previous: float | None) -> dict[str, str]:
    if current is None or previous is None:
        return {"dir": "flat", "label": "—"}
    delta = round(previous - current)  # lower position number = improvement
    if delta > 0:
        return {"dir": "up", "label": f"↑ +{delta}"}
    if delta < 0:
        return {"dir": "down", "label": f"↓ {delta}"}
    return {"dir": "flat", "label": "—"}


def normalize_query(q: str) -> str:
    return " ".join(q.lower().split())


def build_query_index(rows: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    index: dict[str, dict[str, Any]] = {}
    for row in rows:
        key = normalize_query(row["keys"][0])
        index[key] = {
            "position": row.get("position"),
            "impressions": row.get("impressions", 0),
            "clicks": row.get("clicks", 0),
            "ctr": row.get("ctr", 0),
        }
    return index


def pick_gsc_row(index: dict[str, dict[str, Any]], queries: list[str]) -> dict[str, Any] | None:
    best: dict[str, Any] | None = None
    for q in queries:
        row = index.get(normalize_query(q))
        if not row:
            continue
        if best is None or row.get("impressions", 0) > best.get("impressions", 0):
            best = row
    return best


def position_display(avg_position: float | None) -> int | None:
    if avg_position is None:
        return None
    return max(1, round(avg_position))


def get_gsc_service():
    creds_json = os.environ.get("GSC_CREDENTIALS_JSON")
    creds_file = os.environ.get("GSC_CREDENTIALS_FILE")
    if not creds_json and not creds_file:
        return None

    from google.oauth2 import service_account
    from googleapiclient.discovery import build

    if creds_json:
        info = json.loads(creds_json)
        credentials = service_account.Credentials.from_service_account_info(info, scopes=SCOPES)
    else:
        credentials = service_account.Credentials.from_service_account_file(creds_file, scopes=SCOPES)

    return build("searchconsole", "v1", credentials=credentials, cache_discovery=False)


def fetch_query_rows(service, site_url: str, start: str, end: str) -> list[dict[str, Any]]:
    body = {
        "startDate": start,
        "endDate": end,
        "dimensions": ["query"],
        "rowLimit": 25000,
    }
    response = service.searchanalytics().query(siteUrl=site_url, body=body).execute()
    return response.get("rows", [])


def cse_credentials() -> tuple[str, str] | None:
    if os.environ.get("CSE_DISABLED", "").lower() in ("1", "true", "yes"):
        return None
    api_key = os.environ.get("GOOGLE_CSE_API_KEY")
    cx = os.environ.get("GOOGLE_CSE_CX")
    if api_key and cx:
        return api_key, cx
    return None


def domain_from_url(url: str) -> str:
    host = urlparse(url).netloc.lower()
    if host.startswith("www."):
        return host[4:]
    return host


def domain_matches(link: str, target_domain: str) -> bool:
    host = domain_from_url(link)
    target = target_domain.lower()
    return host == target or host.endswith(f".{target}")


def fetch_cse_items(query: str, api_key: str, cx: str, *, max_results: int = 20) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    for start in range(1, max_results + 1, 10):
        params = urllib.parse.urlencode(
            {"key": api_key, "cx": cx, "q": query, "num": 10, "start": start}
        )
        url = f"https://customsearch.googleapis.com/customsearch/v1?{params}"
        try:
            with urllib.request.urlopen(url, timeout=30) as resp:
                data = json.load(resp)
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"CSE HTTP {exc.code} for {query!r}: {body}") from exc
        batch = data.get("items") or []
        items.extend(batch)
        if len(batch) < 10:
            break
        time.sleep(0.3)  # gentle pacing
    return items[:max_results]


def rank_domains_in_serp(
    query: str,
    api_key: str,
    cx: str,
    domains: list[str],
    *,
    max_results: int = 20,
) -> dict[str, int | None]:
    items = fetch_cse_items(query, api_key, cx, max_results=max_results)
    ranks: dict[str, int | None] = {d: None for d in domains}
    for position, item in enumerate(items, start=1):
        link = item.get("link", "")
        for domain in domains:
            if ranks[domain] is None and domain_matches(link, domain):
                ranks[domain] = position
    return ranks


def competitor_ranks_for_keywords(
    config: dict[str, Any], api_key: str, cx: str
) -> dict[str, dict[str, int | None]]:
    competitor_domains = [c["domain"] for c in config["competitors"]]
    id_by_domain = {c["domain"]: c["id"] for c in config["competitors"]}
    out: dict[str, dict[str, int | None]] = {}

    for kw in config["keywords"]:
        domain_ranks = rank_domains_in_serp(kw["phrase"], api_key, cx, competitor_domains)
        out[kw["phrase"]] = {id_by_domain[d]: domain_ranks[d] for d in competitor_domains}
        print(f"  CSE {kw['phrase']!r}: {out[kw['phrase']]}")

    return out


def profile_domain_to_id(config: dict[str, Any]) -> dict[str, str]:
    mapping: dict[str, str] = {}
    for comp in config["competitors"]:
        mapping[comp["domain"]] = comp["id"]
        mapping[comp.get("short", "")] = comp["id"]
    for profile in config.get("competitorProfiles", []):
        url = profile.get("url", "")
        for comp in config["competitors"]:
            if url == comp["domain"] or url.startswith(comp["short"]):
                mapping[url] = comp["id"]
    return mapping


def refresh_competitor_profiles(
    config: dict[str, Any], ranks_by_phrase: dict[str, dict[str, int | None]]
) -> list[dict[str, Any]]:
    phrase_to_short = {kw["phrase"]: kw["competitorShort"] for kw in config["keywords"] if kw.get("competitorShort")}

    domain_to_id = profile_domain_to_id(config)
    profiles = deepcopy(config.get("competitorProfiles", []))

    for profile in profiles:
        comp_id = domain_to_id.get(profile.get("url", ""))
        if not comp_id:
            continue
        for chip in profile.get("keywords", []):
            short = chip.get("short")
            for phrase, ranks in ranks_by_phrase.items():
                if phrase_to_short.get(phrase) == short:
                    chip["rank"] = ranks.get(comp_id)
        present = sum(1 for chip in profile.get("keywords", []) if chip.get("rank") is not None)
        profile.pop("presentOn", None)
        if present and present < len(config["keywords"]):
            profile["presentOn"] = present

    return profiles


def test_cse() -> int:
    creds = cse_credentials()
    if not creds:
        print("Set GOOGLE_CSE_API_KEY and GOOGLE_CSE_CX, then retry.", file=sys.stderr)
        print("See docs/SEO-DASHBOARD-SETUP.md", file=sys.stderr)
        return 1
    api_key, cx = creds
    try:
        items = fetch_cse_items("museum planning", api_key, cx, max_results=5)
    except RuntimeError as exc:
        print(f"CSE test failed: {exc}", file=sys.stderr)
        print(
            "\nGoogle closed Custom Search JSON API to new projects (2025–2026).\n"
            "Skip CSE — use GSC for your ranks + manual competitor SERP in seo-dashboard-config.json.\n"
            "See docs/SEO-DASHBOARD-SETUP.md",
            file=sys.stderr,
        )
        return 1
    print(f"CSE OK — {len(items)} results for 'museum planning':")
    for i, item in enumerate(items, 1):
        print(f"  {i}. {domain_from_url(item.get('link', ''))} — {item.get('title', '')[:60]}")
    return 0


def build_rankings(
    config: dict[str, Any], *, gsc_available: bool, cse_available: bool
) -> dict[str, Any]:
    site_url = os.environ.get("GSC_SITE_URL") or config.get("gscSiteUrl", "sc-domain:museumplanning.com")
    (cur_start, cur_end), (prev_start, prev_end) = period_ranges()

    previous_output: dict[str, Any] | None = None
    if OUTPUT_FILE.exists():
        previous_output = load_json(OUTPUT_FILE)

    current_index: dict[str, dict[str, Any]] = {}
    previous_index: dict[str, dict[str, Any]] = {}

    if gsc_available:
        service = get_gsc_service()
        if service is None:
            gsc_available = False
        else:
            try:
                current_index = build_query_index(fetch_query_rows(service, site_url, cur_start, cur_end))
                previous_index = build_query_index(fetch_query_rows(service, site_url, prev_start, prev_end))
            except Exception as exc:  # noqa: BLE001 — surface API errors clearly
                print(f"GSC API error: {exc}", file=sys.stderr)
                gsc_available = False

    cse_ranks_by_phrase: dict[str, dict[str, int | None]] | None = None
    if cse_available:
        creds = cse_credentials()
        if creds is None:
            cse_available = False
        else:
            api_key, cx = creds
            try:
                print("Fetching competitor ranks via Custom Search API…")
                cse_ranks_by_phrase = competitor_ranks_for_keywords(config, api_key, cx)
            except RuntimeError as exc:
                print(f"CSE error: {exc}", file=sys.stderr)
                if "does not have the access to Custom Search JSON API" in str(exc):
                    print(
                        "Tip: add CSE_DISABLED=1 to tools/launch.env to skip this on future runs.",
                        file=sys.stderr,
                    )
                cse_available = False

    keywords_out = []
    for kw in config["keywords"]:
        gsc_row = pick_gsc_row(current_index, kw["gscQueries"]) if gsc_available else None
        prev_row = pick_gsc_row(previous_index, kw["gscQueries"]) if gsc_available else None

        you = position_display(gsc_row["position"]) if gsc_row else None

        # Fall back to last published snapshot, then config seed
        if you is None and previous_output:
            for old in previous_output.get("keywords", []):
                if old.get("phrase") == kw["phrase"] and old.get("you") is not None:
                    you = old["you"]
                    break
        if you is None and kw.get("fallbackYou") is not None:
            you = kw["fallbackYou"]

        if cse_ranks_by_phrase and kw["phrase"] in cse_ranks_by_phrase:
            comp_ranks = cse_ranks_by_phrase[kw["phrase"]]
        else:
            comp_ranks = kw["competitorRanks"]

        keywords_out.append(
            {
                "phrase": kw["phrase"],
                "pillarUrl": kw["pillarUrl"],
                "volume": kw["volume"],
                "volumeTier": kw["volumeTier"],
                "you": you,
                "ranks": comp_ranks,
                "mom": mom_delta(
                    gsc_row["position"] if gsc_row else None,
                    prev_row["position"] if prev_row else None,
                ),
                "gsc": {
                    "avgPosition": round(gsc_row["position"], 1) if gsc_row and gsc_row.get("position") is not None else None,
                    "impressions": gsc_row.get("impressions") if gsc_row else None,
                    "clicks": gsc_row.get("clicks") if gsc_row else None,
                    "ctr": round(gsc_row["ctr"], 4) if gsc_row and gsc_row.get("ctr") is not None else None,
                    "period": {"start": cur_start, "end": cur_end},
                }
                if gsc_available
                else None,
            }
        )

    competitor_profiles = (
        refresh_competitor_profiles(config, cse_ranks_by_phrase)
        if cse_ranks_by_phrase
        else config["competitorProfiles"]
    )
    comp_as_of = date.today().isoformat() if cse_available else config.get("competitorRanksAsOf")
    comp_note = (
        "Google Custom Search API (automated)"
        if cse_available
        else config.get("competitorRanksNote", "Manual SERP check")
    )

    parts = []
    if gsc_available:
        parts.append(f"Your ranks: Google Search Console ({cur_start} – {cur_end})")
    else:
        parts.append("Your ranks: last snapshot / seed (connect GSC for live data)")
    if cse_available:
        parts.append(f"Competitors: Custom Search API ({comp_as_of})")
    else:
        parts.append(f"Competitors: manual SERP ({config.get('competitorRanksAsOf', 'see config')})")
    data_source = " · ".join(parts)

    return {
        "property": config["property"],
        "reportDate": date.today().isoformat(),
        "dataSource": data_source,
        "gscConnected": gsc_available,
        "cseConnected": cse_available,
        "competitors": config["competitors"],
        "keywords": keywords_out,
        "competitorProfiles": competitor_profiles,
        "opportunities": config["opportunities"],
        "competitorRanksAsOf": comp_as_of,
        "competitorRanksNote": comp_note,
    }


def test_gsc() -> int:
    service = get_gsc_service()
    if service is None:
        print("Set GSC_CREDENTIALS_FILE in tools/launch.env, then retry.", file=sys.stderr)
        print("See docs/GSC-SETUP.md", file=sys.stderr)
        return 1

    config = load_json(CONFIG_FILE) if CONFIG_FILE.exists() else {}
    site_url = os.environ.get("GSC_SITE_URL") or config.get("gscSiteUrl", "sc-domain:museumplanning.com")

    try:
        sites = service.sites().list().execute().get("siteEntry", [])
    except Exception as exc:  # noqa: BLE001
        print(f"GSC auth failed: {exc}", file=sys.stderr)
        return 1

    print("GSC connected. Properties this service account can access:")
    for entry in sites:
        mark = " ← configured" if entry.get("siteUrl") == site_url else ""
        print(f"  {entry.get('siteUrl')} ({entry.get('permissionLevel')}){mark}")

    if not any(e.get("siteUrl") == site_url for e in sites):
        print(f"\nWarning: {site_url!r} not in list.", file=sys.stderr)
        print("Add the service account email in Search Console → Settings → Users.", file=sys.stderr)
        if sites:
            print(f"Try GSC_SITE_URL={sites[0].get('siteUrl')!r} if you use a URL-prefix property.", file=sys.stderr)
        return 1

    (cur_start, cur_end), _ = period_ranges()
    rows = fetch_query_rows(service, site_url, cur_start, cur_end)
    index = build_query_index(rows)
    sample = pick_gsc_row(index, ["museum planning"]) or {}

    print(f"\nSample query 'museum planning' ({cur_start} – {cur_end}):")
    if sample:
        print(f"  avg position: {sample.get('position', '—')}")
        print(f"  impressions:  {sample.get('impressions', 0)}")
        print(f"  clicks:       {sample.get('clicks', 0)}")
    else:
        print("  No impressions for this query in the last 28 days (may be normal for low volume).")

    print("\nGSC OK — run: python3 tools/fetch_gsc_rankings.py")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Build SEO dashboard rankings.json from GSC + CSE + config.")
    parser.add_argument("--dry-run", action="store_true", help="Skip all APIs; merge config with existing snapshot.")
    parser.add_argument("--test-cse", action="store_true", help="Test Custom Search API credentials and exit.")
    parser.add_argument("--test-gsc", action="store_true", help="Test Search Console API credentials and exit.")
    args = parser.parse_args()

    if args.test_cse:
        return test_cse()
    if args.test_gsc:
        return test_gsc()

    if not CONFIG_FILE.exists():
        print(f"Missing config: {CONFIG_FILE}", file=sys.stderr)
        return 1

    config = load_json(CONFIG_FILE)
    gsc_available = not args.dry_run and (
        bool(os.environ.get("GSC_CREDENTIALS_JSON")) or bool(os.environ.get("GSC_CREDENTIALS_FILE"))
    )
    cse_available = not args.dry_run and cse_credentials() is not None

    rankings = build_rankings(config, gsc_available=gsc_available, cse_available=cse_available)
    save_json(OUTPUT_FILE, rankings)
    save_embed_js(EMBED_FILE, rankings)

    mode = []
    if rankings["gscConnected"]:
        mode.append("GSC")
    if rankings.get("cseConnected"):
        mode.append("CSE")
    if not mode:
        mode.append("dry-run/config")
    print(f"Wrote {OUTPUT_FILE} ({'+'.join(mode)}, {len(rankings['keywords'])} keywords)")
    print(f"Wrote {EMBED_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
